### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by Hesesses** [shubhi1407/ng2-notify-popup#2]
npm install --save ng2-popup-notify
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/7.8.0/bin/node" "/usr/local/bin/npm" "install" "--save" "ng2-popup-notify"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/ng2-popup-notify
npm ERR! 404
npm ERR! 404  'ng2-popup-notify' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

Edit.
The install tutorial had this, ng2-notify-popup is the correct name to use :)

**Comment by shubhi1407** [comment]
Sorry for the typo in README. Corrected
